---
title: "Ch. 2"
---

# Set options {-}

```{r setup, message = F}
#| code-fold: true

# set global knit options
knitr::opts_chunk$set(echo = T,
                      eval = T,
                      error = F,
                      warning = F,
                      message = F,
                      cache = T)

# suppress scientific notation
options(scipen=999)

# list of required packages
packages <- c( #"SIN", # this package was removed from the CRAN repository
               "MASS", "dplyr", "tidyr", "purrr", "extraDistr", "ggplot2", "loo", "bridgesampling", "brms", "bayesplot", "tictoc", "hypr", "bcogsci", "papaja", "grid", "kableExtra", "gridExtra", "lme4", "cowplot", "pdftools", "cmdstanr", "rootSolve", "rstan"
  )

# NB: if you haven't already installed bcogsci through devtools, it won't be loaded
## Now load or install & load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)

# this is also required, taken from the textbook

## Save compiled models:
rstan_options(auto_write = FALSE)
## Parallelize the chains using all the cores:
options(mc.cores = parallel::detectCores())
# To solve some conflicts between packages
select <- dplyr::select
extract <- rstan::extract
```

# Chapter 2 - Intro to Bayesian data analysis

#### 2.3 Conjugate forms 2 {-}

Suppose you have $n$ independent and identically distributed data points from the Geometric distribution, which has the likelihood function

\begin{equation}
f(x|\theta)=\theta(1-\theta)^{\sum_{i=1}^n x_i}
\end{equation}

where the data points $x$ can have values 0,1,2,. Let the prior on $\theta$ be $Beta(a,b)$, a beta distribution with parameters a,b. The posterior distribution is a beta distribution with parameters a* and b*. Determine these parameters in terms of $a, b,$ and $\sum_{i=1}^n x_i$.

My work:

- prior is $Beta(a,b)$
- likelihood is $\theta(1-\theta)\sum_{i=1}^n x_i$
- posterior up to proportionality is$[\theta^{a-1}(1-\theta)^{b-1}][\theta(1-\theta)\sum_{i=1}^n x_i$
- sum up the exponentials on either side (and if there's no exponential then add a +1 cause every number is to the power of 1): $\theta^{a + 1 - 1}(1-\theta)^{b + \sum_{i=1}^n x_i - 1}$
- and cancel out the $^{-1}$: $\theta^{a + 1}(1-\theta)^{b + \sum_{i=1}^n x_i}$

# Chapter 3 


